[View in Colaboratory](https://colab.research.google.com/github/ujjwalsharma9/minor-proj/blob/master/40Att_1.ipynb)

In [3]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"ujjwalsharma72","key":"98a037e261e3febbb6f60b9c9070ae47"}'}

In [4]:
!pip install kaggle


    100% |████████████████████████████████| 61kB 2.2MB/s 
    100% |████████████████████████████████| 235kB 4.8MB/s 
  Running setup.py bdist_wheel for kaggle ... - \ done
  Stored in directory: /root/.cache/pip/wheels/44/2c/df/22a6eeb780c36c28190faef6252b739fdc47145fd87a6642d4
  Running setup.py bdist_wheel for python-slugify ... - done
  Stored in directory: /root/.cache/pip/wheels/e3/65/da/2045deea3098ed7471eca0e2460cfbd3fdfe8c1d6fa6fcac92
Successfully built kaggle python-slugify


In [5]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 /root/.kaggle/kaggle.json
!kaggle datasets download -d jessicali9530/celeba-dataset

 99% 1.20G/1.21G [00:09<00:00, 160MB/s]
100% 1.21G/1.21G [00:09<00:00, 138MB/s]


In [0]:
import zipfile
with zipfile.ZipFile("/content/celeba-dataset.zip","r") as zip_ref:
    zip_ref.extractall("/content")

In [1]:
import pandas as pd  

data=pd.read_csv('/content/list_attr_celeba.csv')

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202599 entries, 0 to 202598
Data columns (total 41 columns):
image_id               202599 non-null object
5_o_Clock_Shadow       202599 non-null int64
Arched_Eyebrows        202599 non-null int64
Attractive             202599 non-null int64
Bags_Under_Eyes        202599 non-null int64
Bald                   202599 non-null int64
Bangs                  202599 non-null int64
Big_Lips               202599 non-null int64
Big_Nose               202599 non-null int64
Black_Hair             202599 non-null int64
Blond_Hair             202599 non-null int64
Blurry                 202599 non-null int64
Brown_Hair             202599 non-null int64
Bushy_Eyebrows         202599 non-null int64
Chubby                 202599 non-null int64
Double_Chin            202599 non-null int64
Eyeglasses             202599 non-null int64
Goatee                 202599 non-null int64
Gray_Hair              202599 non-null int64
Heavy_Makeup           202599 non

In [2]:
data.columns

Index(['image_id', '5_o_Clock_Shadow', 'Arched_Eyebrows', 'Attractive',
       'Bags_Under_Eyes', 'Bald', 'Bangs', 'Big_Lips', 'Big_Nose',
       'Black_Hair', 'Blond_Hair', 'Blurry', 'Brown_Hair', 'Bushy_Eyebrows',
       'Chubby', 'Double_Chin', 'Eyeglasses', 'Goatee', 'Gray_Hair',
       'Heavy_Makeup', 'High_Cheekbones', 'Male', 'Mouth_Slightly_Open',
       'Mustache', 'Narrow_Eyes', 'No_Beard', 'Oval_Face', 'Pale_Skin',
       'Pointy_Nose', 'Receding_Hairline', 'Rosy_Cheeks', 'Sideburns',
       'Smiling', 'Straight_Hair', 'Wavy_Hair', 'Wearing_Earrings',
       'Wearing_Hat', 'Wearing_Lipstick', 'Wearing_Necklace',
       'Wearing_Necktie', 'Young'],
      dtype='object')

In [3]:
data.columns[1]

'5_o_Clock_Shadow'

In [0]:
col_list=data.columns.tolist()
col_list.remove('image_id')

In [5]:
col_list

['5_o_Clock_Shadow',
 'Arched_Eyebrows',
 'Attractive',
 'Bags_Under_Eyes',
 'Bald',
 'Bangs',
 'Big_Lips',
 'Big_Nose',
 'Black_Hair',
 'Blond_Hair',
 'Blurry',
 'Brown_Hair',
 'Bushy_Eyebrows',
 'Chubby',
 'Double_Chin',
 'Eyeglasses',
 'Goatee',
 'Gray_Hair',
 'Heavy_Makeup',
 'High_Cheekbones',
 'Male',
 'Mouth_Slightly_Open',
 'Mustache',
 'Narrow_Eyes',
 'No_Beard',
 'Oval_Face',
 'Pale_Skin',
 'Pointy_Nose',
 'Receding_Hairline',
 'Rosy_Cheeks',
 'Sideburns',
 'Smiling',
 'Straight_Hair',
 'Wavy_Hair',
 'Wearing_Earrings',
 'Wearing_Hat',
 'Wearing_Lipstick',
 'Wearing_Necklace',
 'Wearing_Necktie',
 'Young']

In [12]:
len(col_list)

40

In [0]:
import zipfile
with zipfile.ZipFile("/content/img_align_celeba.zip","r") as zip_ref:
    zip_ref.extractall("/content")

In [0]:
import glob
import numpy as np

import os.path as path
from scipy import misc

IMAGE_PATH = '/content/img_align_celeba'
file_paths = glob.glob(path.join(IMAGE_PATH, '00*.jpg'))

images = [misc.imread(path) for path in file_paths]
images = np.asarray(images)

In [0]:
n_images = images.shape[0]
labels = []

for i in range(n_images):
    filename = path.basename(file_paths[i])
    index=int(filename.split(".")[0])
    label_list=[]
    for col in col_list:
      if data[col][index-1]==1:
        label_list.append(col)
    labels.append(label_list)

In [8]:
labels

[['Big_Lips', 'Male', 'Mouth_Slightly_Open', 'No_Beard', 'Wearing_Hat'],
 ['Attractive',
  'Heavy_Makeup',
  'High_Cheekbones',
  'Mouth_Slightly_Open',
  'No_Beard',
  'Smiling',
  'Wearing_Lipstick',
  'Young'],
 ['Brown_Hair',
  'High_Cheekbones',
  'Mouth_Slightly_Open',
  'No_Beard',
  'Smiling',
  'Wavy_Hair',
  'Wearing_Necklace',
  'Young'],
 ['Black_Hair', 'Blurry', 'Male', 'No_Beard', 'Pointy_Nose', 'Young'],
 ['Bags_Under_Eyes',
  'Bangs',
  'Big_Nose',
  'High_Cheekbones',
  'Male',
  'Mouth_Slightly_Open',
  'Narrow_Eyes',
  'No_Beard',
  'Smiling',
  'Wearing_Earrings',
  'Young'],
 ['Arched_Eyebrows',
  'Attractive',
  'Brown_Hair',
  'Heavy_Makeup',
  'No_Beard',
  'Smiling',
  'Wearing_Earrings',
  'Wearing_Lipstick',
  'Young'],
 ['Attractive',
  'Bangs',
  'Narrow_Eyes',
  'No_Beard',
  'Pointy_Nose',
  'Wearing_Lipstick',
  'Young'],
 ['Attractive',
  'Brown_Hair',
  'Heavy_Makeup',
  'High_Cheekbones',
  'Mouth_Slightly_Open',
  'No_Beard',
  'Oval_Face',
  'Smilin

In [9]:
from sklearn.preprocessing import MultiLabelBinarizer
labels = np.array(labels)
labels

array([list(['Big_Lips', 'Male', 'Mouth_Slightly_Open', 'No_Beard', 'Wearing_Hat']),
       list(['Attractive', 'Heavy_Makeup', 'High_Cheekbones', 'Mouth_Slightly_Open', 'No_Beard', 'Smiling', 'Wearing_Lipstick', 'Young']),
       list(['Brown_Hair', 'High_Cheekbones', 'Mouth_Slightly_Open', 'No_Beard', 'Smiling', 'Wavy_Hair', 'Wearing_Necklace', 'Young']),
       ...,
       list(['Attractive', 'Blond_Hair', 'High_Cheekbones', 'Mouth_Slightly_Open', 'No_Beard', 'Oval_Face', 'Pointy_Nose', 'Smiling', 'Straight_Hair', 'Wearing_Earrings', 'Wearing_Lipstick', 'Young']),
       list(['High_Cheekbones', 'Mouth_Slightly_Open', 'Narrow_Eyes', 'No_Beard', 'Smiling', 'Wearing_Hat', 'Wearing_Necklace', 'Young']),
       list(['5_o_Clock_Shadow', 'Bags_Under_Eyes', 'Black_Hair', 'Male', 'Pointy_Nose', 'Sideburns', 'Wavy_Hair', 'Wearing_Necktie', 'Young'])],
      dtype=object)

In [10]:
mlb = MultiLabelBinarizer()
labels = mlb.fit_transform(labels)
 
# loop over each of the possible class labels and show them
for (i, label) in enumerate(mlb.classes_):
	print("{}. {}".format(i + 1, label))

1. 5_o_Clock_Shadow
2. Arched_Eyebrows
3. Attractive
4. Bags_Under_Eyes
5. Bald
6. Bangs
7. Big_Lips
8. Big_Nose
9. Black_Hair
10. Blond_Hair
11. Blurry
12. Brown_Hair
13. Bushy_Eyebrows
14. Chubby
15. Double_Chin
16. Eyeglasses
17. Goatee
18. Gray_Hair
19. Heavy_Makeup
20. High_Cheekbones
21. Male
22. Mouth_Slightly_Open
23. Mustache
24. Narrow_Eyes
25. No_Beard
26. Oval_Face
27. Pale_Skin
28. Pointy_Nose
29. Receding_Hairline
30. Rosy_Cheeks
31. Sideburns
32. Smiling
33. Straight_Hair
34. Wavy_Hair
35. Wearing_Earrings
36. Wearing_Hat
37. Wearing_Lipstick
38. Wearing_Necklace
39. Wearing_Necktie
40. Young


In [11]:
labels

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 1],
       [0, 0, 0, ..., 1, 0, 1],
       ...,
       [0, 0, 1, ..., 0, 0, 1],
       [0, 0, 0, ..., 1, 0, 1],
       [1, 0, 0, ..., 0, 1, 1]])

In [12]:
labels.shape

(9999, 40)

In [0]:
X_train=images[2000:]/255
y_train=labels[2000:]

X_test=images[:2000]/255
y_test=labels[:2000]

In [14]:
from keras.models import Sequential
from keras.layers.normalization import BatchNormalization
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.layers.core import Activation
from keras.layers.core import Flatten
from keras.layers.core import Dropout
from keras.layers.core import Dense
from keras.optimizers import SGD

model = Sequential()
model.add(Conv2D(filters=16, kernel_size=2, padding='same', activation='relu', 
                        input_shape=(218, 178, 3)))
model.add(MaxPooling2D(pool_size=2))
model.add(Conv2D(filters=32, kernel_size=2, padding='same', activation='relu'))
model.add(MaxPooling2D(pool_size=2))
model.add(Conv2D(filters=64, kernel_size=2, padding='same', activation='relu'))
model.add(MaxPooling2D(pool_size=2))
model.add(Dropout(0.3))
model.add(Flatten())
model.add(Dense(500, activation='relu'))
model.add(Dropout(0.4))
model.add(Dense(y_train.shape[1], activation='sigmoid'))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='binary_crossentropy',
              optimizer=sgd)
model.summary()
model.fit(X_train, y_train, epochs=50, batch_size=200)

preds = model.predict(X_test)

Using TensorFlow backend.


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 218, 178, 16)      208       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 109, 89, 16)       0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 109, 89, 32)       2080      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 54, 44, 32)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 54, 44, 64)        8256      
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 27, 22, 64)        0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 27, 22, 64)        0         
__________

In [15]:
preds

array([[0.01460711, 0.01682081, 0.06701959, ..., 0.02790435, 0.01334479,
        0.75372183],
       [0.04404245, 0.32578218, 0.7753972 , ..., 0.25320238, 0.01182113,
        0.90183747],
       [0.01676524, 0.443065  , 0.7767569 , ..., 0.25978935, 0.00479454,
        0.84134156],
       ...,
       [0.0619824 , 0.41509333, 0.878838  , ..., 0.0316032 , 0.03015179,
        0.92749345],
       [0.02014034, 0.5481854 , 0.8070873 , ..., 0.33234742, 0.00910101,
        0.8534414 ],
       [0.06495128, 0.35587516, 0.57768404, ..., 0.37013382, 0.01009436,
        0.8705774 ]], dtype=float32)

In [16]:
preds=np.round(preds, 2)
preds

array([[0.01, 0.02, 0.07, ..., 0.03, 0.01, 0.75],
       [0.04, 0.33, 0.78, ..., 0.25, 0.01, 0.9 ],
       [0.02, 0.44, 0.78, ..., 0.26, 0.  , 0.84],
       ...,
       [0.06, 0.42, 0.88, ..., 0.03, 0.03, 0.93],
       [0.02, 0.55, 0.81, ..., 0.33, 0.01, 0.85],
       [0.06, 0.36, 0.58, ..., 0.37, 0.01, 0.87]], dtype=float32)

In [0]:
preds[preds>=0.5] = 1
preds[preds<0.5] = 0

In [0]:
score=np.sum(preds==y_test)/(preds==y_test).size

In [19]:
score

0.862075